spring:
  application:
    name: test-service
#org.zalando.logbook.Logbook: trace

logbook:
  strategy: default
  exclude:
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**
  format:
    style: json
  body:
    max-size: 3000
    filters:
      string: phone,email,name,passport,answer,query
      number: latitude,longitude,lat,lon
  headers:
    enabled: false
  logger:
    active: true
